"""Config - إعدادات المشروع"""
from .constants import (
    PROJECT_ROOT, DB_PATH, OLLAMA_URL, DEFAULT_LOCAL_MODEL,
    DEFAULT_PROVIDER, ALLOWED_TOOLS, DANGEROUS_TOOLS, SYSTEM_PROMPT,
)

__all__ = [
    "PROJECT_ROOT", "DB_PATH", "OLLAMA_URL", "DEFAULT_LOCAL_MODEL",
    "DEFAULT_PROVIDER", "ALLOWED_TOOLS", "DANGEROUS_TOOLS", "SYSTEM_PROMPT",
]
